# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TalWTNDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  pod 'JWT'
  # Pods for TalWTNDemo

  target 'TalWTNDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TalWTNDemoUITests' do
    # Pods for testing
  end

end
